import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // পাথ ঠিক রাখুন

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter', 
})

export const metadata: Metadata = {
  title: "Ivory Port",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children} {/* এখানে নেভবার/ফুটার থাকবে না */}
      </body>
    </html>
  );
}